### ISSUE TITLE
Invalid login details

### ISSUE THREAD

**Issue by erib1998** [Alanaktion/MCHostPanel#33]
I followed step by step installation to the point of creating an administrator user, after that I get a box that allows me to return to the panel.
The problem is when I want to start session, because when I press the button "log in" only is refreshed, after a few minutes I try again and appears "Invalid login details."

**Comment by pchard** [comment]
remove the data/users/whatevername.json file and run install again.

**Comment by kreezxil** [comment]
The problem is in the security section of inc/lib.php I think it has to do with most Linux distributions are now on higher versions of php such that what was relied up on to make the security doesn't actually work anymore.

If you don't care about security change the last two functions in inc/lib.ph to read
```php
// Securely encrypt a password
function bcrypt($str) {
/*
        $salt = strtr(base64_salt(22),'+','.');
        $work = 13;
        $salt = sprintf('$2y$%s$%s',$work,$salt);
        $hash = crypt($str,$salt);
        if(strlen($hash)>13)
                return $hash;
        else
                return false;
*/
return $str;
}

// Verify a bcrypt-encyrpted string
function bcrypt_verify($str,$hash) {
        return $str == $hash;
}

```
and then you will be able to log in and out consistently.

I did not submit this as a pull request because it is a dirty hack. If someone can come up with a reliable way to make the security work despite the version of php or any salting and encrypting mechanism, then please rewrite these functions to handle that and that is what should be PR'd.
